CREATE TABLE IF NOT EXISTS users(
   user_id bigserial PRIMARY KEY,
   username TEXT NOT NULL,
   password VARCHAR (50) NOT NULL,
   email VARCHAR (300) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS events(
   session_id bigserial PRIMARY KEY,
   name TEXT,
   domain TEXT,
   hostname TEXT,
   pathname TEXT,
   user_id bigint,
   session_id bigint,
   referrer TEXT,
   referrer_source TEXT,
   utm_medium TEXT,
   utm_source TEXT,
   utm_campaign TEXT,
   country_code VARCHAR (2),
   screen_size TEXT,
   operating_system TEXT,
   operating_system_version TEXT,
   browser TEXT,
   browser_version TEXT,
   ts TIMESTAMP,
);
CREATE TABLE IF NOT EXISTS sessions(
   session_id bigserial PRIMARY KEY,
   sign integer,
   domain TEXT,
   user_id bigint,
   hostname TEXT,
   is_bounce boolean,
   entry_page TEXT,
   exit_page TEXT,
   pageviews integer,
   events integer,
   duration integer,
   referrer TEXT,
   referrer_source TEXT,
   country_code VARCHAR (2),
   screen_size TEXT,
   operating_system TEXT,
   browser TEXT,
   start TIMESTAMP,
   ts TIMESTAMP,
);
SELECT create_hypertable('events', 'ts', if_not_exists = > TRUE);
SELECT create_hypertable('sessions', 'start', if_not_exists = > TRUE);