version: '3.4'

services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    environment: 
      POSTGRES_PASSWORD: yukio
      POSTGRES_USER: yukio
      POSTGRES_DB: analytics
    ports: 
      - 5432:5432
